import type {
  Product,
  Service,
  ProductCategory,
  ServiceCategory,
  Testimonial,
  GalleryImage,
  LegalDocument,
} from "./types"

export const productCategories: ProductCategory[] = [
  {
    id: "1",
    name: "Electronics",
    slug: "electronics",
    description: "High-quality electronic products and devices",
    image: "/electronics-category-modern.jpg",
  },
  {
    id: "2",
    name: "Industrial",
    slug: "industrial",
    description: "Industrial-grade equipment and machinery",
    image: "/industrial-equipment-modern.jpg",
  },
  {
    id: "3",
    name: "Office",
    slug: "office",
    description: "Modern office solutions and supplies",
    image: "/office-equipment-modern.jpg",
  },
]

export const products: Product[] = [
  {
    id: "1",
    name: "Enterprise Server Pro",
    description: "High-performance server solution for enterprise workloads. Built for reliability and scalability.",
    specifications: ["64 Core CPU", "512GB RAM", "10TB NVMe Storage", "Redundant PSU"],
    price: 12999,
    cost: 9500,
    discount: 10,
    image: "/enterprise-server-hardware-modern.jpg",
    category: "electronics",
    isVisible: true,
    showPrice: true,
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    name: "Industrial Automation Kit",
    description: "Complete automation solution for manufacturing lines. Includes sensors, controllers, and software.",
    specifications: ["PLC Controller", "12 Sensors", "HMI Display", "Cloud Integration"],
    price: 8499,
    cost: 6200,
    image: "/industrial-automation-kit-modern.jpg",
    category: "industrial",
    isVisible: true,
    showPrice: true,
    createdAt: new Date("2024-02-20"),
  },
  {
    id: "3",
    name: "Smart Office Hub",
    description: "Centralized office management system with IoT connectivity and analytics dashboard.",
    specifications: ["WiFi 6E", "Bluetooth 5.3", "PoE Support", "Mobile App"],
    price: 1299,
    image: "/smart-office-hub-device-modern.jpg",
    category: "office",
    isVisible: true,
    showPrice: true,
    createdAt: new Date("2024-03-10"),
  },
  {
    id: "4",
    name: "Network Security Appliance",
    description: "Enterprise-grade firewall and intrusion detection system with AI-powered threat analysis.",
    specifications: ["10Gbps Throughput", "Zero Trust Architecture", "ML Threat Detection", "24/7 Monitoring"],
    price: 4599,
    discount: 15,
    image: "/network-security-appliance-hardware.jpg",
    category: "electronics",
    isVisible: true,
    showPrice: true,
    createdAt: new Date("2024-03-25"),
  },
  {
    id: "5",
    name: "Precision CNC Machine",
    description: "High-precision computer numerical control machine for manufacturing applications.",
    specifications: ["5-Axis Movement", "0.001mm Precision", "Auto Tool Change", "CAD Integration"],
    price: 45000,
    image: "/cnc-machine-industrial-modern.jpg",
    category: "industrial",
    isVisible: true,
    showPrice: false,
    createdAt: new Date("2024-04-05"),
  },
  {
    id: "6",
    name: "Ergonomic Workstation",
    description: "Height-adjustable desk with integrated cable management and wellness features.",
    specifications: ["Electric Lift", "Memory Presets", "USB-C Hub", "Anti-Fatigue Mat"],
    price: 1899,
    discount: 5,
    image: "/ergonomic-workstation-desk-modern.jpg",
    category: "office",
    isVisible: true,
    showPrice: true,
    createdAt: new Date("2024-04-18"),
  },
]

export const serviceCategories: ServiceCategory[] = [
  {
    id: "1",
    name: "Consulting",
    slug: "consulting",
    description: "Strategic business and technology consulting",
  },
  {
    id: "2",
    name: "Implementation",
    slug: "implementation",
    description: "System setup, deployment, and integration services",
  },
  {
    id: "3",
    name: "Support",
    slug: "support",
    description: "Ongoing maintenance and technical support",
  },
]

export const services: Service[] = [
  {
    id: "1",
    name: "AI Strategy Consulting",
    description:
      "Comprehensive AI adoption strategy tailored to your business needs. We analyze your operations and identify opportunities for AI integration.",
    image: "/ai-consulting-business-meeting-modern.jpg",
    category: "consulting",
    tags: ["AI-Powered", "Strategic", "Enterprise"],
    isVisible: true,
    createdAt: new Date("2024-01-10"),
  },
  {
    id: "2",
    name: "Cloud Infrastructure Setup",
    description:
      "End-to-end cloud infrastructure deployment on AWS, Azure, or GCP. Includes security hardening and cost optimization.",
    image: "/cloud-infrastructure-data-center-modern.jpg",
    category: "implementation",
    tags: ["Cloud", "DevOps", "Security"],
    isVisible: true,
    createdAt: new Date("2024-02-05"),
  },
  {
    id: "3",
    name: "24/7 Technical Support",
    description:
      "Round-the-clock technical support with guaranteed response times. Dedicated account manager and priority escalation.",
    image: "/technical-support-team-office-modern.jpg",
    category: "support",
    tags: ["24/7", "Premium", "Dedicated"],
    isVisible: true,
    createdAt: new Date("2024-02-20"),
  },
  {
    id: "4",
    name: "Digital Transformation",
    description:
      "Complete digital transformation journey from assessment to implementation. Modernize your legacy systems and processes.",
    image: "/digital-transformation-technology-modern.jpg",
    category: "consulting",
    tags: ["Transformation", "Modernization", "Advanced"],
    isVisible: true,
    createdAt: new Date("2024-03-15"),
  },
  {
    id: "5",
    name: "Custom Software Development",
    description:
      "Bespoke software solutions built to your exact specifications. Agile development with continuous delivery.",
    image: "/software-development-coding-modern.jpg",
    category: "implementation",
    tags: ["Custom", "Agile", "Full-Stack"],
    isVisible: true,
    createdAt: new Date("2024-04-01"),
  },
  {
    id: "6",
    name: "Managed Security Services",
    description:
      "Comprehensive security monitoring, threat detection, and incident response. Protect your digital assets 24/7.",
    image: "/cybersecurity-monitoring-center-modern.jpg",
    category: "support",
    tags: ["Security", "Managed", "Compliance"],
    isVisible: true,
    createdAt: new Date("2024-04-20"),
  },
]

export const testimonials: Testimonial[] = [
  {
    id: "1",
    quote:
      "Their enterprise solutions transformed our operations. We saw a 40% increase in efficiency within the first quarter.",
    author: "Sarah Chen",
    role: "CTO",
    company: "TechFlow Inc.",
    logo: "/placeholder.svg?height=60&width=120",
    rating: 5,
    isVerified: true,
    createdAt: new Date("2024-03-01"),
  },
  {
    id: "2",
    quote: "True partners in business innovation. Their team understood our needs and delivered beyond expectations.",
    author: "Michael Rodriguez",
    role: "CEO",
    company: "GlobalSync",
    logo: "/placeholder.svg?height=60&width=120",
    rating: 5,
    isVerified: true,
    createdAt: new Date("2024-02-15"),
  },
  {
    id: "3",
    quote: "The support team is exceptional. Any issue we have is resolved within hours, not days.",
    author: "Emily Watson",
    role: "IT Director",
    company: "Nexus Corp",
    rating: 5,
    isVerified: true,
    createdAt: new Date("2024-04-10"),
  },
]

export const galleryImages: GalleryImage[] = [
  {
    id: "1",
    title: "Annual Conference 2024",
    url: "/placeholder.svg?height=600&width=800",
    category: "events",
    createdAt: new Date(),
  },
  {
    id: "2",
    title: "Product Launch",
    url: "/placeholder.svg?height=600&width=800",
    category: "events",
    createdAt: new Date(),
  },
  {
    id: "3",
    title: "Server Room",
    url: "/placeholder.svg?height=600&width=800",
    category: "products",
    createdAt: new Date(),
  },
  {
    id: "4",
    title: "Automation Demo",
    url: "/placeholder.svg?height=600&width=800",
    category: "products",
    createdAt: new Date(),
  },
  {
    id: "5",
    title: "Team Workshop",
    url: "/placeholder.svg?height=600&width=800",
    category: "services",
    createdAt: new Date(),
  },
  {
    id: "6",
    title: "Client Meeting",
    url: "/placeholder.svg?height=600&width=800",
    category: "services",
    createdAt: new Date(),
  },
  {
    id: "7",
    title: "Headquarters",
    url: "/placeholder.svg?height=600&width=800",
    category: "office",
    createdAt: new Date(),
  },
  {
    id: "8",
    title: "Open Office",
    url: "/placeholder.svg?height=600&width=800",
    category: "office",
    createdAt: new Date(),
  },
]

export const legalDocuments: LegalDocument[] = [
  {
    id: "1",
    name: "GST Registration Certificate",
    description: "Official GST registration documentation",
    fileUrl: "#",
    fileType: "pdf",
    category: "gst",
    createdAt: new Date(),
  },
  {
    id: "2",
    name: "Certificate of Incorporation",
    description: "Company incorporation documents",
    fileUrl: "#",
    fileType: "pdf",
    category: "ownership",
    createdAt: new Date(),
  },
  {
    id: "3",
    name: "Service Level Agreement",
    description: "Standard SLA for all service contracts",
    fileUrl: "#",
    fileType: "pdf",
    category: "service",
    createdAt: new Date(),
  },
  {
    id: "4",
    name: "Product Warranty Terms",
    description: "Warranty terms and conditions for products",
    fileUrl: "#",
    fileType: "pdf",
    category: "product",
    createdAt: new Date(),
  },
]
